"""
PIB Study Generator
Compact MCQ PDF renderer.

IMPORTANT:
The MCQ renderer deliberately uses the SAME page geometry as the
Summary / Quick Revision renderer.

Only the content formatting differs.

Layout:
- A4
- 8mm top/bottom
- 14mm left/right
- compact PIB header
- blue divider
- 79% study column
- 21% Notes column
- dashed Notes separator
"""

from pathlib import Path
import html
import re
import sys
import webbrowser

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)

from . import style_config as style
from .generate_summary import (
    get_logo_path,
    format_date_str,
    safe_inline,
)


# ============================================================
# BASIC HELPERS
# ============================================================

def open_pdf(path):
    """
    Open generated PDF using the default Windows PDF viewer.
    """

    try:
        webbrowser.open(
            Path(path).resolve().as_uri()
        )
    except Exception:
        pass


def normalize_lines(data):
    if data is None:
        return []

    text = str(data)

    text = text.replace(
        "\r\n",
        "\n",
    ).replace(
        "\r",
        "\n",
    )

    return [
        line.rstrip()
        for line in text.split("\n")
    ]


# ============================================================
# HTML / MARKDOWN CLEANING
# ============================================================

def strip_html(text):
    """
    Remove accidental HTML generated by the AI.

    This prevents tags such as:
        <div>
        <span>
        <br>
        <strong>
    from appearing in the final PDF.
    """

    text = str(text)

    text = re.sub(
        r"<br\s*/?>",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"</p\s*>",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"<[^>]+>",
        "",
        text,
    )

    return html.unescape(text)


def clean_text(text):
    """
    Plain text cleanup for MCQ parser.
    """

    text = strip_html(text)

    # Remove markdown emphasis markers.
    text = re.sub(
        r"\*\*([^*]+)\*\*",
        r"\1",
        text,
    )

    text = re.sub(
        r"__([^_]+)__",
        r"\1",
        text,
    )

    text = re.sub(
        r"(?<!\*)\*([^*]+)\*(?!\*)",
        r"\1",
        text,
    )

    text = re.sub(
        r"(?<!_)_([^_]+)_(?!_)",
        r"\1",
        text,
    )

    # Collapse excessive whitespace.
    text = re.sub(
        r"[ \t]+",
        " ",
        text,
    )

    return text.strip()


# ============================================================
# MCQ BLOCK SPLITTING
# ============================================================

def split_mcq_blocks(text):
    """
    Split MCQ content into individual questions.

    A question begins ONLY when a line starts with:
        1.
        2.
        3.

    This is intentionally strict so that:
        Statement 1:
        Statement 2:
        (a)
        (b)
    are NOT incorrectly treated as new questions.
    """

    lines = normalize_lines(text)

    starts = []

    for index, line in enumerate(lines):

        if re.match(
            r"^\s*\d+\.\s+\S",
            line,
        ):
            starts.append(index)

    if not starts:

        stripped = str(
            text or ""
        ).strip()

        return [stripped] if stripped else []

    blocks = []

    for position, start in enumerate(starts):

        if position + 1 < len(starts):
            end = starts[position + 1]
        else:
            end = len(lines)

        block = "\n".join(
            lines[start:end]
        ).strip()

        if block:
            blocks.append(block)

    return blocks


# ============================================================
# QUESTION NUMBER
# ============================================================

def extract_question_number(block):
    """
    Extract:
        1. Question text

    into:
        ("1", "Question text")
    """

    match = re.match(
        r"^\s*(\d+)\.\s*(.*)$",
        block,
        flags=re.DOTALL,
    )

    if not match:
        return "", block.strip()

    return (
        match.group(1),
        match.group(2).strip(),
    )


# ============================================================
# ANSWER / EXPLANATION
# ============================================================

def split_answer_explanation(text):
    """
    Separate:

        Answer: (b)
        Explanation: ...

    from the question.
    """

    answer_match = re.search(
        r"(?im)^\s*Answer\s*:\s*(.+?)\s*$",
        text,
    )

    if not answer_match:

        explanation_match = re.search(
            r"(?im)^\s*Explanation\s*:\s*",
            text,
        )

        if explanation_match:

            question_part = (
                text[:explanation_match.start()]
                .strip()
            )

            explanation = (
                text[
                    explanation_match.end():
                ].strip()
            )

            return (
                question_part,
                "",
                explanation,
            )

        return (
            text.strip(),
            "",
            "",
        )

    question_part = (
        text[:answer_match.start()]
        .strip()
    )

    answer = (
        answer_match.group(1)
        .strip()
    )

    remaining = (
        text[answer_match.end():]
        .strip()
    )

    explanation_match = re.search(
        r"(?im)^\s*Explanation\s*:\s*",
        remaining,
    )

    if explanation_match:

        explanation = (
            remaining[
                explanation_match.end():
            ].strip()
        )

    else:

        explanation = remaining

    return (
        question_part,
        answer,
        explanation,
    )


# ============================================================
# STATEMENTS
# ============================================================

def extract_statements(text):
    """
    Extract:

        Statement 1: ...
        Statement 2: ...
        Statement 3: ...

    without confusing them with question numbers.
    """

    pattern = re.compile(
        r"(?im)^\s*Statement\s+(\d+)\s*:\s*"
    )

    matches = list(
        pattern.finditer(text)
    )

    if not matches:
        return [], text

    statements = []

    for index, match in enumerate(matches):

        start = match.end()

        if index + 1 < len(matches):

            end = matches[
                index + 1
            ].start()

        else:

            # Stop at the first option or answer.
            remainder = text[start:]

            stop_match = re.search(
                r"(?im)^\s*"
                r"(?:"
                r"\([abcd]\)"
                r"|Answer\s*:"
                r"|Explanation\s*:"
                r")",
                remainder,
            )

            if stop_match:
                end = (
                    start
                    + stop_match.start()
                )
            else:
                end = len(text)

        statement_text = text[
            start:end
        ].strip()

        statement_text = clean_text(
            statement_text
        )

        statements.append(
            (
                match.group(1),
                statement_text,
            )
        )

    # Remove statement block from question text.
    first_start = matches[0].start()

    before = text[
        :first_start
    ].strip()

    after = text[
        matches[-1].end():
    ]

    # Remove the last statement body from the
    # remaining question text.
    last_stop = re.search(
        r"(?im)^\s*"
        r"(?:"
        r"\([abcd]\)"
        r"|Answer\s*:"
        r"|Explanation\s*:"
        r")",
        after,
    )

    if last_stop:

        remaining = after[
            last_stop.start():
        ].strip()

    else:

        remaining = ""

    if before and remaining:
        question_text = (
            before
            + "\n"
            + remaining
        )
    elif before:
        question_text = before
    else:
        question_text = remaining

    return (
        statements,
        question_text.strip(),
    )


# ============================================================
# OPTIONS
# ============================================================

def extract_options(text):
    """
    Extract options:

        (a) ...
        (b) ...
        (c) ...
        (d) ...

    Options may be on separate lines or accidentally placed
    on the same line.
    """

    pattern = re.compile(
        r"(?im)(?:^|\s)"
        r"(\([abcd]\))"
        r"\s*"
    )

    matches = list(
        pattern.finditer(text)
    )

    if not matches:
        return [], text.strip()

    options = []

    for index, match in enumerate(matches):

        label = (
            match.group(1)
            .lower()
        )

        start = match.end()

        if index + 1 < len(matches):

            end = matches[
                index + 1
            ].start()

        else:

            end = len(text)

        option_text = text[
            start:end
        ].strip()

        option_text = clean_text(
            option_text
        )

        options.append(
            (
                label,
                option_text,
            )
        )

    question_text = text[
        :matches[0].start()
    ].strip()

    return (
        options,
        question_text,
    )


# ============================================================
# PARSE ONE MCQ
# ============================================================

def parse_mcq(block):
    """
    Convert a raw MCQ block into a structured dictionary.
    """

    number, body = (
        extract_question_number(
            block
        )
    )

    (
        main_content,
        answer,
        explanation,
    ) = split_answer_explanation(
        body
    )

    (
        statements,
        main_without_statements,
    ) = extract_statements(
        main_content
    )

    (
        options,
        question_text,
    ) = extract_options(
        main_without_statements
    )

    question_text = clean_text(
        question_text
    )

    answer = clean_text(
        answer
    )

    explanation = clean_text(
        explanation
    )

    return {
        "number": number,
        "question": question_text,
        "statements": statements,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }


# ============================================================
# MCQ CONTENT STYLES
# ============================================================

def mcq_question_paragraph(number, question):
    """
    Render:
        1. Which of the following...
    """

    if not question:
        return None

    if number:

        text = (
            f"<b>{number}.</b> "
            f"{safe_inline(question)}"
        )

    else:

        text = safe_inline(
            question
        )

    return Paragraph(
        text,
        style.MCQ_QUESTION_STYLE,
    )


def mcq_statement_paragraph(
    number,
    statement,
):
    """
    Render:
        Statement 1: ...
    """

    return Paragraph(
        (
            f"<b>Statement {number}:</b> "
            f"{safe_inline(statement)}"
        ),
        style.MCQ_STATEMENT_STYLE,
    )


def build_options_table(options):
    """
    Render MCQ options in a clean 2-column grid.

    Example:

    (a) Option A                 (b) Option B
    (c) Option C                 (d) Option D
    """

    if not options:
        return None

    content_width = (
        A4[0]
        - style.MARGIN_LEFT
        - style.MARGIN_RIGHT
    )

    main_width = (
        content_width
        * style.CONTENT_COLUMN_RATIO
        - style.CONTENT_RIGHT_PADDING
    )

    column_width = (
        main_width / 2
    )

    cells = []

    for label, option_text in options:

        cell = Paragraph(
            (
                f"<b>{safe_inline(label)}</b> "
                f"{safe_inline(option_text)}"
            ),
            style.MCQ_OPTION_STYLE,
        )

        cells.append(cell)

    rows = []

    for index in range(
        0,
        len(cells),
        2,
    ):

        left = cells[index]

        if index + 1 < len(cells):
            right = cells[index + 1]
        else:
            right = Paragraph(
                "",
                style.MCQ_OPTION_STYLE,
            )

        rows.append(
            [
                left,
                right,
            ]
        )

    table = Table(
        rows,
        colWidths=[
            column_width,
            column_width,
        ],
        hAlign="LEFT",
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    0,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    style.MCQ_OPTION_GAP,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    0,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    1,
                ),
            ]
        )
    )

    return table


# ============================================================
# ANSWER BOX
# ============================================================

def build_answer_box(answer):
    if not answer:
        return None

    content_width = (
        A4[0]
        - style.MARGIN_LEFT
        - style.MARGIN_RIGHT
    )

    main_width = (
        content_width
        * style.CONTENT_COLUMN_RATIO
        - style.CONTENT_RIGHT_PADDING
    )

    paragraph = Paragraph(
        (
            "<b>Answer:</b> "
            f"{safe_inline(answer)}"
        ),
        style.MCQ_ANSWER_STYLE,
    )

    table = Table(
        [[paragraph]],
        colWidths=[
            main_width
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    style.MCQ_ANSWER_BACKGROUND,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    style.MCQ_ANSWER_BORDER,
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
            ]
        )
    )

    return table


# ============================================================
# EXPLANATION BOX
# ============================================================

def build_explanation_box(
    explanation
):
    if not explanation:
        return None

    content_width = (
        A4[0]
        - style.MARGIN_LEFT
        - style.MARGIN_RIGHT
    )

    main_width = (
        content_width
        * style.CONTENT_COLUMN_RATIO
        - style.CONTENT_RIGHT_PADDING
    )

    paragraph = Paragraph(
        (
            "<b>Explanation:</b> "
            f"{safe_inline(explanation)}"
        ),
        style.MCQ_EXPLANATION_STYLE,
    )

    table = Table(
        [[paragraph]],
        colWidths=[
            main_width
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    style.MCQ_EXPLANATION_BACKGROUND,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    style.MCQ_EXPLANATION_BORDER,
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    3,
                ),
            ]
        )
    )

    return table


# ============================================================
# ONE QUESTION → FLOWABLES
# ============================================================

def build_question_story(question):
    """
    Build one complete MCQ.

    The question, statements, options, answer and explanation
    are kept together where ReportLab can fit them.
    """

    elements = []

    number = question.get(
        "number",
        "",
    )

    question_text = question.get(
        "question",
        "",
    )

    statements = question.get(
        "statements",
        [],
    )

    options = question.get(
        "options",
        [],
    )

    answer = question.get(
        "answer",
        "",
    )

    explanation = question.get(
        "explanation",
        "",
    )

    # --------------------------------------------------------
    # Question
    # --------------------------------------------------------

    question_paragraph = (
        mcq_question_paragraph(
            number,
            question_text,
        )
    )

    if question_paragraph:

        elements.append(
            question_paragraph
        )

    # --------------------------------------------------------
    # Statements
    # --------------------------------------------------------

    for statement_number, statement in statements:

        elements.append(
            mcq_statement_paragraph(
                statement_number,
                statement,
            )
        )

    # --------------------------------------------------------
    # Options
    # --------------------------------------------------------

    options_table = (
        build_options_table(
            options
        )
    )

    if options_table:

        elements.append(
            Spacer(
                1,
                1,
            )
        )

        elements.append(
            options_table
        )

    # --------------------------------------------------------
    # Answer
    # --------------------------------------------------------

    answer_box = (
        build_answer_box(
            answer
        )
    )

    if answer_box:

        elements.append(
            Spacer(
                1,
                2,
            )
        )

        elements.append(
            answer_box
        )

    # --------------------------------------------------------
    # Explanation
    # --------------------------------------------------------

    explanation_box = (
        build_explanation_box(
            explanation
        )
    )

    if explanation_box:

        elements.append(
            Spacer(
                1,
                2,
            )
        )

        elements.append(
            explanation_box
        )

    # --------------------------------------------------------
    # Small gap before next question
    # --------------------------------------------------------

    elements.append(
        Spacer(
            1,
            style.MCQ_BLOCK_SPACE_AFTER,
        )
    )

    return elements


# ============================================================
# HEADER
# ============================================================

def draw_header(canvas, doc):

    page_width, page_height = A4

    left = style.MARGIN_LEFT

    right = (
        page_width
        - style.MARGIN_RIGHT
    )

    top = (
        page_height
        - style.MARGIN_TOP
    )

    # --------------------------------------------------------
    # Logo
    # --------------------------------------------------------

    logo_path = get_logo_path()

    if logo_path:

        try:

            from reportlab.lib.utils import (
                ImageReader
            )

            image = ImageReader(
                str(logo_path)
            )

            image_width, image_height = (
                image.getSize()
            )

            target_width = (
                style.HEADER_LOGO_WIDTH
            )

            target_height = (
                target_width
                * image_height
                / image_width
            )

            canvas.drawImage(
                image,
                left,
                top - target_height,
                width=target_width,
                height=target_height,
                preserveAspectRatio=True,
                mask="auto",
            )

        except Exception:
            pass

    # --------------------------------------------------------
    # Header title
    # --------------------------------------------------------

    title_x = (
        left
        + style.HEADER_LOGO_CELL_WIDTH
    )

    title = getattr(
        doc,
        "_pib_header_title",
        style.BRAND_NAME,
    )

    canvas.setFont(
        style.BODY_BOLD_FONT,
        style.HEADER_TITLE_SIZE,
    )

    canvas.setFillColor(
        style.HEADER_TITLE_COLOR
    )

    max_width = (
        right
        - title_x
    )

    words = title.split()

    lines = []
    current = ""

    for word in words:

        candidate = (
            word
            if not current
            else f"{current} {word}"
        )

        if (
            canvas.stringWidth(
                candidate,
                style.BODY_BOLD_FONT,
                style.HEADER_TITLE_SIZE,
            )
            <= max_width
        ):

            current = candidate

        else:

            if current:
                lines.append(
                    current
                )

            current = word

    if current:
        lines.append(
            current
        )

    title_y = top - 12

    for line in lines[:2]:

        canvas.drawString(
            title_x,
            title_y,
            line,
        )

        title_y -= (
            style.HEADER_TITLE_LEADING
        )

    # --------------------------------------------------------
    # Blue divider
    # --------------------------------------------------------

    divider_y = (
        top
        - max(
            30,
            len(lines[:2])
            * style.HEADER_TITLE_LEADING
            + 8,
        )
    )

    canvas.setStrokeColor(
        style.HEADER_DIVIDER_COLOR
    )

    canvas.setLineWidth(
        style.HEADER_DIVIDER_WIDTH
    )

    canvas.line(
        left,
        divider_y,
        right,
        divider_y,
    )

    # --------------------------------------------------------
    # Date
    # --------------------------------------------------------

    date_text = getattr(
        doc,
        "_pib_date_text",
        "",
    )

    if date_text:

        canvas.setFont(
            style.BODY_FONT,
            7.5,
        )

        canvas.setFillColor(
            style.NOTES_TEXT_COLOR
        )

        canvas.drawRightString(
            right,
            divider_y - 10,
            date_text,
        )

    # --------------------------------------------------------
    # Notes separator
    # --------------------------------------------------------

    usable_width = (
        page_width
        - style.MARGIN_LEFT
        - style.MARGIN_RIGHT
    )

    separator_x = (
        style.MARGIN_LEFT
        + usable_width
        * style.CONTENT_COLUMN_RATIO
    )

    canvas.setStrokeColor(
        style.NOTES_SEPARATOR_COLOR
    )

    canvas.setLineWidth(
        style.NOTES_SEPARATOR_WIDTH
    )

    canvas.setDash(
        2,
        2,
    )

    canvas.line(
        separator_x,
        divider_y - 3,
        separator_x,
        style.MARGIN_BOTTOM + 3,
    )

    canvas.setDash()

    # --------------------------------------------------------
    # Notes label
    # --------------------------------------------------------

    notes_center = (
        separator_x
        + usable_width
        * style.NOTES_COLUMN_RATIO
        / 2
    )

    canvas.setFont(
        style.BODY_FONT,
        style.NOTES_TEXT_SIZE,
    )

    canvas.setFillColor(
        style.NOTES_TEXT_COLOR
    )

    canvas.drawCentredString(
        notes_center,
        divider_y - 16,
        "NOTES",
    )


# ============================================================
# FOOTER
# ============================================================

def draw_footer(canvas, doc):

    page_width, _ = A4

    left = style.MARGIN_LEFT

    right = (
        page_width
        - style.MARGIN_RIGHT
    )

    footer_y = 4.5 * style.mm

    canvas.setFont(
        style.BODY_FONT,
        style.FOOTER_FONT_SIZE,
    )

    canvas.setFillColor(
        style.FOOTER_COLOR
    )

    canvas.drawString(
        left,
        footer_y,
        style.BRAND_NAME,
    )

    canvas.drawRightString(
        right,
        footer_y,
        f"Page {doc.page}",
    )


def draw_page(canvas, doc):

    canvas.saveState()

    draw_header(
        canvas,
        doc,
    )

    draw_footer(
        canvas,
        doc,
    )

    canvas.restoreState()


# ============================================================
# DOCUMENT
# ============================================================

class PIBMCQDocTemplate(
    BaseDocTemplate
):

    def __init__(
        self,
        filename,
        header_title,
        date_text="",
    ):

        super().__init__(
            filename,
            pagesize=A4,
            leftMargin=style.MARGIN_LEFT,
            rightMargin=style.MARGIN_RIGHT,

            # EXACT SAME HEADER SPACE AS SUMMARY.
            topMargin=(
                style.MARGIN_TOP
                + 34
            ),

            bottomMargin=(
                style.MARGIN_BOTTOM
                + 4
            ),

            title=header_title,
            author=style.BRAND_NAME,
        )

        usable_width = (
            A4[0]
            - style.MARGIN_LEFT
            - style.MARGIN_RIGHT
        )

        main_width = (
            usable_width
            * style.CONTENT_COLUMN_RATIO
            - style.CONTENT_RIGHT_PADDING
        )

        frame_height = (
            A4[1]
            - self.topMargin
            - self.bottomMargin
        )

        main_frame = Frame(
            style.MARGIN_LEFT,
            self.bottomMargin,
            main_width,
            frame_height,
            leftPadding=0,
            rightPadding=0,
            topPadding=0,
            bottomPadding=0,
            id="PIBMCQMain",
        )

        template = PageTemplate(
            id="PIBMCQ",
            frames=[main_frame],
            onPage=draw_page,
        )

        self.addPageTemplates(
            [template]
        )

        self._pib_header_title = (
            header_title
        )

        self._pib_date_text = (
            date_text
        )


# ============================================================
# PUBLIC GENERATOR
# ============================================================

def generate_mcq_pdf(
    mcq_data,
    output_path=None,
    yymmdd_str="",
):
    """
    Generate compact MCQ PDF.

    Layout is identical to Summary / Quick Revision.
    """

    if output_path is None:
        output_path = Path(
            "mcqs.pdf"
        )

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    date_text = format_date_str(
        yymmdd_str
    )

    document = PIBMCQDocTemplate(
        str(output_path),
        header_title=style.BRAND_NAME,
        date_text=date_text,
    )

    raw_text = str(
        mcq_data or ""
    ).strip()

    blocks = split_mcq_blocks(
        raw_text
    )

    story = []

    # --------------------------------------------------------
    # Parse and render each question.
    # --------------------------------------------------------

    for block in blocks:

        parsed = parse_mcq(
            block
        )

        question_story = (
            build_question_story(
                parsed
            )
        )

        if question_story:

            # Keep the individual question together whenever
            # the question is small enough for one page.
            story.append(
                KeepTogether(
                    question_story
                )
            )

    # --------------------------------------------------------
    # Empty MCQ input
    # --------------------------------------------------------

    if not story:

        story.append(
            Paragraph(
                "No MCQs available.",
                style.BODY_STYLE,
            )
        )

    # --------------------------------------------------------
    # Build PDF
    # --------------------------------------------------------

    document.build(
        story
    )

    return str(
        output_path
    )


# ============================================================
# COMPATIBILITY ALIASES
# ============================================================

generate_mcqs = (
    generate_mcq_pdf
)

generate_mcqs_pdf = (
    generate_mcq_pdf
)


# ============================================================
# COMMAND LINE
# ============================================================

if __name__ == "__main__":

    if len(sys.argv) < 3:

        print(
            "Usage:"
        )

        print(
            "python tools/generate_mcqs.py "
            "INPUT.txt OUTPUT.pdf [DDMMYYYY]"
        )

        raise SystemExit(1)

    input_path = Path(
        sys.argv[1]
    )

    output_path = Path(
        sys.argv[2]
    )

    date_value = (
        sys.argv[3]
        if len(sys.argv) > 3
        else ""
    )

    input_text = (
        input_path
        .read_text(
            encoding="utf-8"
        )
    )

    generated = generate_mcq_pdf(
        input_text,
        output_path=output_path,
        yymmdd_str=date_value,
    )

    print(
        f"Generated: {generated}"
    )